### ISSUE TITLE
Some questions about Safeheron (hope it is ok to put it here as there is no discussion section)

### ISSUE THREAD

**Issue by johnnynanjiang** [Safeheron/safeheron-offline-recovery-tool#11]
Hi Safeheron, we are very interested in your Wallet as a Service product, and would like to build a crypto wallet with it.

Just a couple of questions:

i. Is MPC Wallet as a Service fully open source?
ii. Is Safeheron MPC 2/3 or a decentralized and open source network?

Thanks and regards,
Johnny

**Comment by yan-jie** [comment]
Hi Johnny,

Thanks for contacting Safeheron and I’ve forwarded your inquiry to our BD team.

For further product/features/services inquiries, Jag will be your exclusive BD who also helps you with onboarding Safeheron to enjoy institutional-grade self-custody service!

Please feel free to contact Jag at jagfoo@safeheron.com.

​And, if you want to know more about Safeheron products or have Safeheron better understand your needs, you can schedule a call/meeting(https://calendly.com/jagfoo/30min) with Jag.

**Comment by johnnynanjiang** [comment]
Thanks @yan-jie for your advice.

Yes I'm interested to know more about Safeheron, and have some technical questions about Safeheron's products, especially around `MPC Wallet as a Service`.

I agree with Safeheron's vision and opinions, such as:

[As Web2 Giants Enter the Web3 Space, Security Will be Make-or-Break](https://blog.safeheron.com/blog/insights/safeheron-originals/as-web2-giants-enter-the-web3-space-security-will-be-make-or-break)

[The Future of Crypto Payments](https://blog.safeheron.com/blog/insights/safeheron-originals/the-future-of-crypto-payments)

**Comment by yan-jie** [comment]
Would you like to share more about technical questions you have? Or, you can also feel free to contact Jag Foo who will give you a better picture of our MPC Wallet as a Service.

**Comment by yan-jie** [comment]
Would you like to share more about technical questions you have to support@safeheron.com? Or, you can also feel free to contact Jag Foo who will give you a better picture of our MPC Wallet as a Service.
